title: Nina Austria
description: I am a junior at Lawrence University majoring in Math with a Statistics Track and interested in a career in Data Science.

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
